"""English text for every Thai sentence shown on screen.

The key is the exact Thai source text. A value may be a ``(singular, plural)``
pair, chosen by the ``n`` placeholder. Anything missing falls back to the Thai
text, and ``tests/test_i18n.py`` fails if a sentence in the code has no entry.
"""

EN: dict = {
    # ---- navigation and page titles
    "งานประจำวัน": "Daily work",
    "ลูกค้า": "Clients",
    "ตั้งค่า": "Settings",
    "ภาพรวม": "Overview",
    "เอกสารลูกค้า": "Client documents",
    "งาน": "Tasks",
    "รออนุมัติ": "Awaiting approval",
    "ข้อมูลลูกค้า": "Client records",
    "แจ้งเตือนลูกค้า": "Client notifications",
    "รายงานลูกค้า": "Client reports",
    "ปฏิทินกำหนดยื่น": "Filing calendar",

    # ---- sidebar and header
    "กรณีศึกษา · ข้อมูลทั้งหมดเป็นข้อมูลจำลอง": "Case study · all data is synthetic",
    "ใช้งานในฐานะ": "Working as",
    "ระบบตัวอย่างไม่มีการล็อกอิน เลือกบทบาทเพื่อดูว่าแต่ละคนทำอะไรได้บ้าง":
        "The demo has no login. Pick a person to see what each role can do.",
    "รอบงาน (เดือนของบัญชี)": "Work period (accounting month)",
    "รอบงาน": "Period",
    "วันที่": "Date",
    "ตั้งค่าเดโม": "Demo settings",
    "วันที่จำลอง": "Simulated date",
    "ทุกหน้าคำนวณวันค้างและวันเลยกำหนดจากวันนี้": "Every page counts waiting and overdue days from this date.",
    "เปิดรอบงาน {period}": "Open period {period}",
    "เปิดรอบงาน {period} แล้ว สร้างงาน {n} รายการ": "Opened period {period}: created {n} tasks",
    "ล้างข้อมูลและโหลดข้อมูลตัวอย่างใหม่": "Reset and reload sample data",
    "โหลดข้อมูลตัวอย่างใหม่แล้ว": "Sample data reloaded",

    # ---- units and time
    "{n} งาน": ("{n} task", "{n} tasks"),
    "{n} ราย": ("{n} client", "{n} clients"),
    "{n} วัน": ("{n} day", "{n} days"),
    "{n} ฉบับ": ("{n} document", "{n} documents"),
    "{n} ข้อความ": ("{n} message", "{n} messages"),
    "%d ฉบับ": "%d docs",
    "{a} / {b} ราย": "{a} / {b} clients",
    "อีก {n} วัน": ("{n} day left", "{n} days left"),
    "เลยกำหนด {n} วัน": ("Overdue by {n} day", "Overdue by {n} days"),
    "ครบกำหนดวันนี้": "Due today",
    "ค้างนานสุด {n} วัน": ("Longest wait: {n} day", "Longest wait: {n} days"),
    "ขาด {n} ฉบับ": ("{n} missing", "{n} missing"),
    "ครบแล้ว": "Complete",
    "ทั้งหมด": "All",
    "รวม": "Total",
    "จด": "Registered",
    "มี": "Yes",

    # ---- overview
    "ลูกค้าที่เอกสารยังไม่ครบ": "Clients with documents missing",
    "งานรอเจ้าของตรวจ": "Tasks awaiting owner review",
    "งานเลยกำหนด": "Overdue tasks",
    "กำหนดยื่นถัดไป": "Next filing deadline",
    "กำหนดยื่นถัดไป ({date})": "Next filing deadline ({date})",
    "ยังไม่ยื่น {n} ราย": "{n} not yet filed",
    "ภาระงานที่ยังเปิดอยู่ รายคน": "Open workload per person",
    "นับงานทุกประเภทในรอบนี้ที่ยังไม่เสร็จ ใช้ดูว่าใครงานล้น ใครพอรับเพิ่มได้":
        "Counts every unfinished task in this period, to see who is overloaded and who can take more.",
    "ดูเป็นตาราง": "View as table",
    "กำหนดยื่นภาษีรอบนี้": "Tax filing deadlines this period",
    "รอบนี้ยังไม่มีงานยื่นภาษี": "No tax filing tasks in this period yet",
    "งานของฉันใน 7 วันข้างหน้า": "My tasks in the next 7 days",
    "สำหรับเจ้าของ แสดงงานที่รอตรวจแทน": "For the owner this shows tasks waiting for review instead.",
    "ไม่มีงานเร่งด่วน": "Nothing urgent",
    "จำนวนงาน": "Number of tasks",
    "กำหนดยื่น": "Filing deadline",
    "จำนวน": "Count",
    "ยื่นแล้ว": "Filed",
    "แบบ": "Form",
    "เหลือเวลา": "Time left",
    "กำหนด": "Due",

    # ---- documents
    "ใครยังขาดอะไร": "Who is missing what",
    "บันทึกการรับเอกสาร": "Record received documents",
    "เอกสารครบแล้ว": "Complete",
    "ยังไม่ครบ": "Incomplete",
    "ต้องขอใหม่ (อ่านไม่ออก/ไม่ถูกต้อง)": "Re-request (unreadable or wrong)",
    "แสดงเฉพาะลูกค้าที่เอกสารยังไม่ครบ": "Show only clients with missing documents",
    "ได้รับแล้ว": "Received",
    "ต้องส่ง": "Required",
    "ยังขาด / ต้องขอใหม่": "Missing / re-request",
    "ลูกค้าทุกรายส่งเอกสารครบแล้ว": "Every client has sent all documents",
    "แจ้งเตือนลูกค้าที่ยังขาดเอกสาร": "Remind clients with missing documents",
    "ส่งข้อความเดียวต่อราย บอกเฉพาะชื่อเอกสารที่ยังขาด ทางช่องทางที่ลูกค้าใช้ (LINE หรืออีเมล)":
        "One message per client, naming only the missing documents, sent on the channel the client uses (LINE or email).",
    "ส่งแจ้งเตือน {n} ราย": ("Send reminder to {n} client", "Send reminders to {n} clients"),
    "ส่งแจ้งเตือนแล้ว {n} ราย ดูข้อความได้ที่หน้าแจ้งเตือนลูกค้า":
        ("Reminder sent to {n} client. See the message on the Client notifications page.",
         "Reminders sent to {n} clients. See the messages on the Client notifications page."),
    "แก้สถานะ ช่องทาง หรือหมายเหตุในตาราง แล้วกดบันทึก เอกสารจากทุกช่องทางลงทะเบียนที่นี่ที่เดียว":
        "Edit status, channel or note in the table, then save. Documents from every channel are registered here.",
    "เอกสาร": "Document",
    "สถานะ": "Status",
    "ช่องทางที่ได้รับ": "Received via",
    "หมายเหตุ": "Note",
    "วันที่รับ": "Date received",
    "บันทึก": "Save",
    "ไม่มีการเปลี่ยนแปลง": "No changes",
    "บันทึกแล้ว {n} รายการ": ("Saved {n} change", "Saved {n} changes"),
    "แจ้งลูกค้าอัตโนมัติ: {message}": "Client notified automatically: {message}",
    "ผู้รับผิดชอบ": "Assigned to",
    "ยังไม่ได้รับ": "Not received",
    "ต้องขอใหม่": "Re-request",
    "ระบุช่องทางที่ได้รับเอกสารด้วย": "Say which channel the document came through.",

    # ---- tasks
    "ประเภทงาน": "Task type",
    "ค้นหาลูกค้า": "Search clients",
    "{n} งาน · คลิกที่แถวเพื่อดูรายละเอียดและอัปเดตสถานะ":
        ("{n} task · click a row for details and to update its status",
         "{n} tasks · click a row for details and to update status"),
    "ลูกค้ารายนี้ยังส่งเอกสารเดือนนี้ไม่ครบ ดูรายละเอียดที่หน้าเอกสารลูกค้า":
        "This client has not sent all documents for this month. See the Client documents page.",
    "เจ้าของส่งกลับให้แก้: {reason}": "Owner sent this back: {reason}",
    "ข้อควรระวังของลูกค้ารายนี้: {notes}": "Things to watch for with this client: {notes}",
    "อัปเดตสถานะ": "Update status",
    "งานนี้รอเจ้าของตรวจ เปลี่ยนผู้ใช้เป็นเจ้าของที่แถบด้านซ้ายเพื่ออนุมัติ":
        "This task is waiting for the owner. Switch to the owner in the sidebar to approve it.",
    "งานนี้เสร็จแล้ว": "This task is finished.",
    "บทบาทนี้อัปเดตงานบัญชีไม่ได้": "This role cannot update accounting tasks.",
    "เหตุผลที่ส่งกลับ (ถ้าส่งกลับ)": "Reason for sending back (if sending back)",
    "มอบหมายงาน": "Assign task",
    "งานที่เสร็จแล้วเปลี่ยนผู้รับผิดชอบไม่ได้": "A finished task cannot be reassigned.",
    "เจ้าของเป็นผู้ย้ายงานระหว่างพนักงาน": "Only the owner moves tasks between staff.",
    "ย้ายงานไปให้": "Move task to",
    "ย้ายงาน": "Move task",
    "ย้ายงานไปให้ {name} แล้ว": "Task moved to {name}",
    "ประวัติการเปลี่ยนแปลง": "History",
    "ผู้ทำ": "Done by",
    "การกระทำ": "Action",
    "ผู้รับผิดชอบสำรอง": "Backup",
    "ผู้ยื่น": "Filed by",

    # ---- approvals
    "รอตรวจ": "To review",
    "ค้างนานสุด": "Longest wait",
    "ครบกำหนดภายใน 3 วัน": "Due within 3 days",
    "หน้านี้สำหรับเจ้าของ เลือก 'ใช้งานในฐานะ' เป็นเจ้าของที่แถบด้านซ้ายเพื่ออนุมัติหรือส่งกลับ":
        "This page is for the owner. Choose the owner under 'Working as' in the sidebar to approve or send back.",
    "ไม่มีงานรอตรวจ": "Nothing to review",
    "อนุมัติแล้ว รอพนักงานยื่น": "Approved, waiting to be filed",
    "ส่งโดย {name} · รอมา {n} วัน · กำหนด {date} ({left})":
        ("Submitted by {name} · waiting {n} day · due {date} ({left})",
         "Submitted by {name} · waiting {n} days · due {date} ({left})"),
    "เหตุผลถ้าส่งกลับ": "Reason if sending back",
    "อนุมัติ": "Approve",
    "ส่งกลับ": "Send back",
    "อนุมัติแล้ว: {task} · {client}": "Approved: {task} · {client}",
    "ส่งกลับให้ {name} แก้แล้ว": "Sent back to {name}",

    # ---- calendar
    "กำหนดยื่นของรอบ {period}": "Filing deadlines for {period}",
    "กระดาษ": "Paper",
    "อินเทอร์เน็ต": "Online",
    "สำนักงานใช้": "Office uses",
    "ยื่นทางอินเทอร์เน็ต": "File online",
    "ยื่นแบบกระดาษ": "File on paper",
    "วันกำหนดอ้างอิงปฏิทินภาษีของกรมสรรพากร (rd.go.th) ถ้าตรงวันเสาร์ อาทิตย์ หรือวันหยุดในรายการด้านล่าง ระบบเลื่อนไปวันทำการถัดไปให้อัตโนมัติ":
        "Deadlines follow the Revenue Department tax calendar (rd.go.th). A deadline that falls on a weekend or a holiday listed below moves to the next business day automatically.",
    "เจ้าของเป็นผู้แก้กติกาวันกำหนดและวันหยุด": "Only the owner edits the deadline rules and holidays.",
    "กติกาวันกำหนด": "Deadline rules",
    "สำนักงานยื่นแบบโดย": "The office files by",
    "กระดาษ (วันที่)": "Paper (day of month)",
    "อินเทอร์เน็ต (วันที่)": "Online (day of month)",
    "การขยายเวลายื่นทางอินเทอร์เน็ต 8 วันมาจากประกาศกระทรวงการคลังที่ต่ออายุเป็นช่วง ๆ ถ้าประกาศเปลี่ยน แก้ตัวเลขที่นี่":
        "The 8-day online extension comes from a Ministry of Finance announcement that is renewed from time to time. If it changes, edit the numbers here.",
    "วันหยุดราชการ": "Public holidays",
    "ชื่อวันหยุด": "Holiday name",
    "เพิ่มวันหยุดตามประกาศจริงของแต่ละปี ข้อมูลตัวอย่างใส่ไว้เฉพาะวันที่ตรวจกับปฏิทินกรมสรรพากรแล้ว":
        "Add each year's real holidays. The sample data only includes dates checked against the Revenue Department calendar.",
    "บันทึกและคำนวณกำหนดส่งของงานที่ยังไม่เสร็จใหม่": "Save and recalculate due dates of unfinished tasks",
    "บันทึกแล้ว ปรับกำหนดส่งของงานที่ยังไม่เสร็จ {n} งาน":
        ("Saved. Updated the due date of {n} unfinished task.", "Saved. Updated the due dates of {n} unfinished tasks."),
    "วันหยุดที่ระบบใช้เลื่อนวันกำหนด": "Holidays used to move deadlines",
    "ยังไม่มีวันหยุดในระบบ": "No holidays in the system yet",

    # ---- clients
    "ค้นหาชื่อลูกค้า": "Search client name",
    "{n} ราย · คลิกที่แถวเพื่อดูและแก้ข้อมูลลูกค้า":
        ("{n} client · click a row to view and edit", "{n} clients · click a row to view and edit"),
    "ประเภทธุรกิจ": "Business type",
    "ลูกจ้าง": "Employees",
    "ผู้รับผิดชอบหลัก": "Primary",
    "สำรอง": "Backup",
    "ช่องทางติดต่อ": "Contact channel",
    "สถานะงานรอบนี้": "Tasks this period",
    "เอกสารที่ต้องส่งทุกเดือน": "Documents due every month",
    "แบบภาษีที่ยื่นทุกเดือน": "Tax forms filed every month",
    "ข้อมูลการทำงานกับลูกค้า": "Working details",
    "ช่องทางแจ้งเตือน": "Notification channel",
    "LINE ID / อีเมล": "LINE ID / email",
    "วิธีทำงานและข้อควรระวัง (ให้คนที่รับช่วงต่ออ่านแล้วทำงานต่อได้)":
        "How we work with this client and what to watch for (so whoever takes over can carry on)",
    "บันทึกข้อมูล {name} แล้ว": "Saved {name}",
    "พนักงานบัญชีแก้ได้เฉพาะบันทึกข้อควรระวัง ส่วนผู้รับผิดชอบและช่องทางติดต่อให้เจ้าของหรือธุรการแก้":
        "Accountants can edit only the notes. The owner or admin edits the assignments and contact details.",
    "เปลี่ยนผู้รับผิดชอบหลักมีผลกับงานของรอบที่เปิดใหม่ งานที่มีอยู่แล้วย้ายได้ที่หน้างาน":
        "Changing the primary person applies to periods opened from now on. Move existing tasks on the Tasks page.",
    "ผู้รับผิดชอบหลักและสำรองต้องเป็นคนละคน": "The primary and backup person must be different.",
    "มอบหมายงานบัญชีให้ธุรการไม่ได้": "Accounting tasks cannot be assigned to the admin.",

    # ---- notifications
    "ประเภท": "Type",
    "ช่องทาง": "Channel",
    "ส่งถึง": "Sent to",
    "ข้อความ": "Message",
    "ระบบส่งข้อความหาลูกค้าอัตโนมัติเมื่อสถานะเปลี่ยน: ได้รับเอกสารครบ, ยื่นภาษีแล้ว, ส่งรายงานแล้ว และเมื่อสำนักงานกดเตือนเรื่องเอกสาร ลูกค้าไม่ต้องเข้าระบบ":
        "The system messages clients automatically when a status changes: documents complete, tax filed, report sent, and when the office sends a document reminder. Clients never log in.",
    "ในเดโมนี้ข้อความถูกบันทึกไว้ที่นี่ ไม่ได้ส่งจริง ระบบจริงจะต่อกับ LINE Messaging API และอีเมล ข้อความบอกเฉพาะสถานะ ไม่แนบเอกสารหรือตัวเลขทางการเงิน เพื่อลดความเสี่ยงด้านข้อมูลส่วนบุคคล":
        "In this demo messages are only recorded here, not sent. A real deployment connects to the LINE Messaging API and email. Messages state only the status and never attach documents or financial figures, to reduce personal-data risk.",
    "ข้อความถึงลูกค้าเขียนเป็นภาษาไทยเสมอ ไม่เปลี่ยนตามภาษาของหน้าจอ":
        "Messages to clients are always written in Thai, whatever language the screen is in.",
    "ได้รับเอกสารครบ": "Documents complete",
    "เตือนส่งเอกสาร": "Document reminder",
    "ยื่นภาษีแล้ว": "Tax filed",
    "ส่งรายงานแล้ว": "Report sent",

    # ---- reports
    "ส่งรายงานรอบนี้แล้ว {sent} / {total} ราย · ทุกรายใช้แม่แบบเดียวกัน":
        "Reports sent this period: {sent} / {total} · every client gets the same template",
    "ดาวน์โหลดรายงาน (.md)": "Download report (.md)",
    "ส่งแล้ว": "Sent",
    "ยังไม่ส่ง": "Not sent",
    "พนักงานบัญชีหรือเจ้าของเป็นผู้ส่ง": "Accountants or the owner send reports",
    "บันทึกว่าส่งรายงานให้ลูกค้าแล้ว": "Mark report as sent to client",
    "บันทึกการส่งรายงาน {period} แล้ว": "Recorded: report for {period} sent",
    "รายงานสถานะงานประจำเดือน": "Monthly status report",
    "วันที่ออกรายงาน": "Report date",
    "เอกสารที่ได้รับ": "Documents received",
    "การยื่นแบบภาษี": "Tax filings",
    "วันที่ยื่น": "Date filed",
    "สิ่งที่ต้องดำเนินการต่อ": "Next steps",
    "รายงานนี้สร้างจากระบบติดตามงานโดยอัตโนมัติ": "This report was generated automatically by the job tracker.",
    "รบกวนส่งเอกสารที่ยังขาด": "Please send the missing documents",
    "สำนักงานกำลังดำเนินการ": "The office is working on",
    "ไม่มีรายการที่ต้องดำเนินการ งานประจำเดือนนี้เสร็จครบแล้ว": "Nothing outstanding. This month's work is complete.",

    # ---- statuses, roles, actions
    "เจ้าของ": "Owner",
    "พนักงานบัญชี": "Accountant",
    "ธุรการ": "Admin",
    "ยังไม่เริ่ม": "Not started",
    "กำลังทำ": "In progress",
    "รอเจ้าของตรวจ": "Awaiting owner review",
    "อนุมัติแล้ว รอยื่น": "Approved, ready to file",
    "เสร็จ": "Done",
    "เริ่มทำ": "Start",
    "ส่งให้เจ้าของตรวจ": "Submit for review",
    "ส่งกลับให้แก้": "Send back for changes",
    "บันทึกว่ายื่นแล้ว": "Mark as filed",
    "ทำเสร็จแล้ว": "Mark as done",
    "ทำ '{action}' กับงานสถานะ '{status}' ในบทบาท '{role}' ไม่ได้":
        "'{action}' is not allowed on a task that is '{status}' for the role '{role}'.",
    "ต้องใส่เหตุผลเมื่อส่งงานกลับให้แก้": "A reason is required when sending a task back.",

    # ---- task types, forms, channels
    "บันทึกบัญชี": "Bookkeeping",
    "ภ.ง.ด.1": "PND.1",
    "ภ.ง.ด.3": "PND.3",
    "ภ.ง.ด.53": "PND.53",
    "ภ.พ.30": "PP.30 (VAT)",
    "อีเมล": "Email",
    "ลูกค้ามาส่งเอง": "Client brought it in",

    # ---- sample data
    "รายการเดินบัญชีธนาคาร": "Bank statement",
    "บิล/ใบเสร็จค่าใช้จ่าย": "Expense bills / receipts",
    "ใบกำกับภาษีซื้อ": "Purchase tax invoices",
    "ใบกำกับภาษีขาย": "Sales tax invoices",
    "ใบแจ้งหนี้/ใบเสร็จขาย": "Sales invoices / receipts",
    "สรุปเงินเดือนพนักงาน": "Payroll summary",
    "วันปิยมหาราช": "Chulalongkorn Day",
    "ค้าปลีก": "Retail",
    "ค้าส่ง": "Wholesale",
    "ร้านอาหาร/คาเฟ่": "Restaurant / cafe",
    "บริการ": "Services",
    "ก่อสร้าง": "Construction",
    "ขนส่ง": "Transport",
    "ผลิต": "Manufacturing",
    "ออนไลน์": "Online business",
    "ส่ง statement เป็นรูปถ่ายจาก LINE มักไม่ชัด ให้ขอไฟล์ PDF จากแอปธนาคารแทน":
        "Sends statements as LINE photos that are often unclear. Ask for the PDF from the bank app instead.",
    "มีบัญชีธนาคาร 2 บัญชี (บัญชีขายหน้าร้าน และบัญชีโอนจ่ายซัพพลายเออร์) ต้องขอให้ครบทั้งสองบัญชี":
        "Has two bank accounts (shop sales and supplier payments). Make sure both are collected.",
    "เจ้าของสะดวกคุยช่วงเย็นหลัง 18:00 น. ตอนกลางวันให้ติดต่อผู้จัดการร้าน":
        "The owner is available after 18:00. During the day, contact the shop manager.",
    "ค่าเช่าที่จ่ายให้บุคคลธรรมดาต้องหัก ภ.ง.ด.3 ทุกเดือน ลูกค้ามักลืมส่งหนังสือรับรองการหัก":
        "Rent paid to individuals needs PND.3 withholding every month. The client often forgets to send the withholding certificate.",
    "ใบกำกับภาษีซื้อจากซัพพลายเออร์รายใหญ่มาช้า ประมาณวันที่ 5 ของเดือน":
        "Purchase tax invoices from the main supplier arrive late, around the 5th of the month.",
    "ขายผ่าน marketplace ให้ดาวน์โหลดรายงานยอดขายจากระบบร้านค้าเอง ไม่ต้องรอลูกค้า":
        "Sells on a marketplace. Download the sales report from the seller portal yourself instead of waiting for the client.",
    "มีพนักงานรายวันเปลี่ยนบ่อย ตรวจรายชื่อในสรุปเงินเดือนเทียบเดือนก่อนทุกครั้ง":
        "Daily-wage staff change often. Compare the payroll names with last month every time.",
    "วิไล": "Wilai",
    "สมชาย": "Somchai",
    "นภา": "Napa",
    "กิตติ": "Kitti",
    "ปราณี": "Pranee",
    "สยามรุ่งเรือง": "Siam Rungrueang",
    "ทองดีการค้า": "Thongdee Trading",
    "บ้านสวนฟาร์ม": "Baan Suan Farm",
    "รุ่งอรุณเทรดดิ้ง": "Rungarun Trading",
    "ศรีนครวัสดุ": "Srinakorn Materials",
    "เจริญผลซัพพลาย": "Charoenphon Supply",
    "นำชัยออโต้": "Namchai Auto",
    "ใบไม้เขียวคาเฟ่": "Green Leaf Cafe",
    "ฟ้าใสคลีนนิ่ง": "Fasai Cleaning",
    "มั่นคงก่อสร้าง": "Mankhong Construction",
    "ภูผาทัวร์": "Phupha Tours",
    "ดีไซน์ดีสตูดิโอ": "Design Dee Studio",
    "ข้าวหอมโภชนา": "Khaohom Food",
    "ไทยรักษ์พลาสติก": "Thairak Plastic",
    "สุขใจเฮลท์": "Sukjai Health",
    "เกียรติทองขนส่ง": "Kiattong Transport",
    "พรพิมลแฟชั่น": "Pornpimon Fashion",
    "เมืองเก่ามีเดีย": "Muangkao Media",
    "กรีนเทคโซลูชั่น": "GreenTech Solutions",
    "นาคาเฟอร์นิเจอร์": "Naka Furniture",
    "แสงทองการพิมพ์": "Saengthong Printing",
    "บัวขาวสปา": "Buakhao Spa",
    "ลานนาออร์แกนิก": "Lanna Organic",
    "ชลบุรีซีฟู้ด": "Chonburi Seafood",
    "พัฒนาไอที": "Pattana IT",
    "เรือนไทยโฮมสเตย์": "Ruenthai Homestay",
    "สามพรานเกษตร": "Sampran Agriculture",
    "ปัญญาติวเตอร์": "Panya Tutoring",
    "ดาวเหนือเอ็นจิเนียริ่ง": "Daoneua Engineering",
    "อิ่มสุขเบเกอรี่": "Imsuk Bakery",
    "วิวัฒน์อิเล็กทริก": "Wiwat Electric",
    "ทะเลงามรีสอร์ท": "Thalengam Resort",
    "มิตรภาพการยาง": "Mittrapap Rubber",
    "ช่างดีเซอร์วิส": "Changdee Service",
    "รวมใจสหกิจ": "Ruamjai Cooperative",
    "ใจดีเพ็ทช็อป": "Jaidee Pet Shop",
    "นิยมยนต์พาร์ท": "Niyom Auto Parts",
    "บางกอกบิวตี้": "Bangkok Beauty",
    "ขวัญใจการเกษตร": "Khwanjai Agriculture",
    "เก้าดาวลอจิสติกส์": "Kaodao Logistics",
}
